/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AvgTable: typeof import('./src/components/AvgTable.vue')['default']
    CityMapModal: typeof import('./src/components/CityMapModal.vue')['default']
    CreateMenu: typeof import('./src/components/CreateMenu.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    MerchantMenu: typeof import('./src/components/MerchantMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TBTable: typeof import('./src/components/TBTable.vue')['default']
    TotalTable: typeof import('./src/components/TotalTable.vue')['default']
  }
}
