package com.webEng.api.startup;

import java.io.BufferedReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import com.webEng.api.model.Merchant;
import com.webEng.api.model.Transaction;
import com.webEng.api.repository.RepoMerchant;
import com.webEng.api.repository.RepoTransaction;

/**
 * Class that populates the db with the default data.
 */
@Component
public class CsvDataInit implements CommandLineRunner {

    // definitions
    private final RepoTransaction transactionRepository;
    private final RepoMerchant merchantRepository;
    // Batch for upload
    private static final int BATCH_SIZE = 1000;
    // Path of the csv's
    private static final String CSVPATH = System.getenv().getOrDefault("CSVPATH", "/data");

    /**
     * COnstructor
     * 
     * @param transactionRepository transaction repo
     * @param merchantRepository    merchant repo
     */
    public CsvDataInit(
            RepoTransaction transactionRepository,
            RepoMerchant merchantRepository) {
        this.transactionRepository = transactionRepository;
        this.merchantRepository = merchantRepository;
    }

    /**
     * This is always ran at initialization of the program.
     * Calls the importers if there is no data in the db. Otherwise, it skips it.
     * 
     * This method contains AI generated code. All system prints are AI generated by
     * CLaude.
     */
    @Override
    public void run(String... args) throws Exception {
        System.out.println("=== CsvDataInit starting ===");

        long merchantCount = merchantRepository.count();
        long transactionCount = transactionRepository.count();

        // Prints for debugging
        System.out.println("Current merchant count: " + merchantCount);
        System.out.println("Current transaction count: " + transactionCount);

        if (merchantCount == 0) {
            System.out.println("Starting merchant import");
            importMerchants();
        } else {
            System.out.println("Skipping merchant import - table has " + merchantCount + " records");
        }

        if (transactionCount == 0) {
            System.out.println("Starting transaction import...");
            importTransactions();
        } else {
            System.out.println("Skipping transaction import - table has " + transactionCount + " records");
        }

        System.out.println("=== CsvDataInit complete ===");
    }

    /**
     * Imports the merchants
     * This contains AI generated lines. All System out.prints and .trim() in lines
     * 117 and 118 are generated by claude
     */
    void importMerchants() throws Exception {
        Path path = Paths.get(CSVPATH, "merchants.csv");

        try (BufferedReader reader = Files.newBufferedReader(path)) {
            String line;
            int count = 0;
            int skipped = 0;

            List<Merchant> batch = new ArrayList<>();

            reader.readLine(); // skip header

            while ((line = reader.readLine()) != null) {
                String[] cols = line.split(",");

                if (cols.length < 2) {
                    System.out.println("Skipping invalid line: " + line);
                    skipped++;
                    continue;
                }

                try {
                    Integer externalId = Integer.parseInt(cols[0].trim());

                    // Check if merchant already exists
                    if (merchantRepository.findByExternalMerchantId(externalId).isPresent()) {
                        skipped++;
                        continue;
                    }

                    Merchant merchant = new Merchant();
                    merchant.setExternalId(externalId);
                    merchant.setMerchantCity(cols[1].trim());
                    merchant.setMerchantState(cols.length > 2 ? cols[2].trim() : null);

                    batch.add(merchant);
                    count++;

                    if (batch.size() >= BATCH_SIZE) {
                        merchantRepository.saveAll(batch);
                        batch.clear();
                        System.out.println("Imported " + count + " merchants...");
                    }
                } catch (NumberFormatException e) {
                    System.err.println("Error parsing merchant line: " + line + " - " + e.getMessage());
                    skipped++;
                }
            }
            if (!batch.isEmpty()) {
                merchantRepository.saveAll(batch);
            }

            System.out.println("Merchant import complete: " + count + " imported, " + skipped + " skipped");
        }
    }

    /**
     * Imports the transacrtions
     * 
     */
    void importTransactions() throws Exception {
        Path path = Paths.get(CSVPATH, "transactions.csv");

        try (BufferedReader reader = Files.newBufferedReader(path)) {
            String line;
            int count = 0;
            int skipped = 0;

            List<Transaction> batch = new ArrayList<>();

            reader.readLine(); // header

            while ((line = reader.readLine()) != null) {
                try {
                    Transaction tx = mapTransaction(line);
                    batch.add(tx);
                    count++;

                    if (batch.size() >= BATCH_SIZE) {
                        transactionRepository.saveAll(batch);
                        batch.clear();
                        System.out.println("Imported " + count + " transactions...");
                    }
                } catch (Exception e) {
                    System.err.println("Error processing transaction line: " + line);
                    e.printStackTrace();
                    skipped++;
                }
            }
            if (!batch.isEmpty()) {
                transactionRepository.saveAll(batch);
            }

            System.out.println("Transaction import complete: " + count + " imported, " + skipped + " skipped");
        }
    }

    /**
     * Translates between the csv version and the transaction entity,
     * 
     * @param line The csv line
     * @return Transaction with the csv data.
     */
    private Transaction mapTransaction(String line) {
        String[] cols = line.split(",");

        Transaction tx = new Transaction();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        tx.setTimestamp(LocalDateTime.parse(cols[1], formatter));

        tx.setClientId(Integer.parseInt(cols[2]));
        tx.setAmount(Double.parseDouble(cols[3]));

        Integer merchantCsvId = Integer.parseInt(cols[4]);

        Merchant merchant = merchantRepository
                .findByExternalMerchantId(merchantCsvId)
                .orElseThrow(() -> new IllegalStateException(
                        "Merchant not found for CSV merchant_id=" + merchantCsvId));

        tx.setMerchant(merchant);

        return tx;
    }

}
